version: "3"
services:
  wordpress:
    image: wordpress
    ports:
      - "8081:80"
    depends_on:
      - mysql
    environment:
      - WORDPRESS_DB_HOST: "mysql"
      - WORDPRESS_DB_USER: root
      - WORDPRESS_DB_PASSWORD: "aran"
      - WORDPRESS_DB_NAME: aran
    restart: always
  mysql:
    image: "mysql:5.7"
    environment:
      - MYSQL_DATABASE: "aran"
      - MYSQL_ROOT_PASSWORD: "aran"
    volumes:
      -
